# This workflow will build, test, and deploy both frontend (React/Vitest) and backend (Java/Maven) projects
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests

name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    name: Backend Tests (Java/Maven)

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run backend tests
      run: mvn -B test --file backend/pom.xml

    - name: Build backend with Maven
      run: mvn -B package --file backend/pom.xml

    - name: Backend test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Backend Tests (Maven)
        path: backend/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true

  frontend-tests:
    runs-on: ubuntu-latest
    name: Frontend Tests (React/Vitest)

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      run: npm ci
      working-directory: frontend

    - name: Run frontend tests
      run: npm run test:run
      working-directory: frontend

    - name: Frontend test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Frontend Tests (Vitest)
        path: frontend/test-results.xml
        reporter: java-junit
        fail-on-error: true

  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    needs: [backend-tests, frontend-tests]
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist

    - name: Upload backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-jar
        path: backend/target/*.jar

    - name: Build and Deploy Backend
      run: |
        mvn -B package --file backend/pom.xml
        # Add deployment commands for backend here

    - name: Build and Deploy Frontend
      run: |
        npm ci --prefix frontend
        npm run build --prefix frontend
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist
        cname: # Add your custom domain here if you have one